version: "3.9"

services:
    app:
        build:
            context: .
            args:
                - DEV=true
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
            - dev-static-data:/vol/web
        command: >
            sh -c "python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=devdb
            - DB_USER=devuser
            - DB_PASS=changemetothelatestversion
        depends_on:
            - db

    db:
        image: postgres:13-alpine
        volumes:
            - dev-db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=devdb
            - POSTGRES_USER=devuser
            - POSTGRES_PASSWORD=changemetothelatestversion

volumes:
    dev-db-data:
    dev-static-data:

# NOTES

# orig
# POSTGRES_PASSWORD=changeme


# 1
# https://github.com/LondonAppDeveloper/c2-recipe-app-api-2/compare/s-05-project-setup-05-create-project-dockerfile...s-05-project-setup-07-create-docker-compose-config

# 2
# https://github.com/LondonAppDeveloper/c2-recipe-app-api-2/compare/s-05-project-setup-07-create-docker-compose-config...s-05-project-setup-10-configure-flake8